### ISSUE TITLE
TelephoneField does not accept defaultCountry GB

### ISSUE THREAD

**Issue by tyteen4a03** [NouanceLabs/payload-better-fields-plugin#34] opened 2023-10-28 22:41 UTC
For some reason this causes an error in the admin UI:

```
        ...TelephoneField(
            {
                name: "contactPhoneNumber",
                label: "Default Contact Person Phone Number",
                admin: {
                    placeholder: "+44 123 456 7890",
                },
            },
            {
                defaultCountry: "gb", // this is the line
            },
        ),
```

```
Country not found: gb 
PhoneNumberInput_@http://localhost:3000/admin/main.js:286211:20
```

**Comment by tyteen4a03** [comment] 2023-10-28 22:42
I found the issue: `defaultCountry` is case-sensitive 🤦

**Comment by paulpopus** [comment] 2023-10-31 00:56
Closing as this is not a bug or an issue with the plugin

**Closed by paulpopus** 2023-10-31 00:56 UTC
